apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-exporter
  namespace: logcollect

spec:
  template:
    spec:
      containers:
      - name: azure-devops-exporter
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/azure-devops-exporter:tag_placeholder